"use client"

import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Navbar } from "@/components/landing/navbar"
import { Footer } from "@/components/landing/footer"
import { ChevronDown, HelpCircle, Sparkles } from "lucide-react"
import Link from "next/link"
import { Button } from "@/components/ui/button"

const faqs = [
  {
    category: "General",
    questions: [
      {
        q: "What is SkillTwin?",
        a: "SkillTwin is an AI-powered skill gap analyzer that helps students bridge the gap between their education and employment. It analyzes your curriculum, GitHub portfolio, and CGPA against live job market demands to create a personalized learning roadmap."
      },
      {
        q: "How does SkillTwin work?",
        a: "SkillTwin uses multiple AI agents (Ollama, Groq, Gemini) to analyze your profile. It compares your skills with real job requirements, identifies gaps, and generates a personalized roadmap with resources to help you become job-ready."
      },
      {
        q: "Is SkillTwin free to use?",
        a: "Yes! SkillTwin is completely free to use. We believe every student deserves access to quality career guidance without financial barriers."
      },
      {
        q: "Who can use SkillTwin?",
        a: "SkillTwin is designed for students, fresh graduates, and anyone looking to transition into tech roles. Whether you're studying computer science or self-learning, SkillTwin helps you identify and fill skill gaps."
      }
    ]
  },
  {
    category: "Analysis",
    questions: [
      {
        q: "What information do I need to provide?",
        a: "You need to provide: your target job role, CGPA, syllabus topics/skills you've learned, projects you've worked on, and optionally your GitHub username for portfolio analysis."
      },
      {
        q: "How accurate is the skill matching?",
        a: "Our AI uses semantic matching and understands synonyms (e.g., JS = JavaScript, ML = Machine Learning). The accuracy improves with more detailed input about your skills and projects."
      },
      {
        q: "How long does the analysis take?",
        a: "The analysis typically takes 10-30 seconds. Our multi-agent system runs in parallel to provide comprehensive results as quickly as possible."
      },
      {
        q: "What job roles are supported?",
        a: "We currently support: Full Stack Developer, Frontend Developer, Backend Developer, ML Engineer, Data Scientist, DevOps Engineer, Mobile App Developer, and Cloud Architect. More roles are being added regularly."
      }
    ]
  },
  {
    category: "GitHub Integration",
    questions: [
      {
        q: "Why should I connect my GitHub?",
        a: "Connecting GitHub allows us to analyze your actual projects, coding languages, and contributions. This provides a more accurate assessment of your practical skills beyond what's on your resume."
      },
      {
        q: "What GitHub data do you access?",
        a: "We only access public repository data: languages used, repository topics, star counts, and contribution activity. We never access private repositories or sensitive information."
      },
      {
        q: "Is my GitHub data stored?",
        a: "No, we don't store your GitHub data. It's fetched in real-time during analysis and discarded after generating your results."
      }
    ]
  },
  {
    category: "Roadmap & Jobs",
    questions: [
      {
        q: "How is the learning roadmap generated?",
        a: "The roadmap is generated by our Groq AI agent, which creates a phased learning plan based on your missing skills. It includes specific resources, timelines, and milestones tailored to your target role."
      },
      {
        q: "Are the job listings real?",
        a: "Yes! Job listings are fetched in real-time from JSearch API, which aggregates jobs from LinkedIn, Indeed, Glassdoor, and other major platforms."
      },
      {
        q: "How is the job match percentage calculated?",
        a: "Match percentage is calculated by comparing your skills with the job requirements. Higher matches mean you have more of the required skills for that position."
      },
      {
        q: "Can I apply for jobs directly from SkillTwin?",
        a: "Yes! Each job listing includes a direct 'Apply Now' link that takes you to the original job posting where you can submit your application."
      }
    ]
  },
  {
    category: "Technical",
    questions: [
      {
        q: "What AI models power SkillTwin?",
        a: "SkillTwin uses multiple AI agents: Ollama (Mistral) for skill analysis, Groq (Llama3) for roadmap generation, Google Gemini for career advice, and GitHub API for portfolio analysis."
      },
      {
        q: "Do I need to install anything?",
        a: "For users, no installation is required - just use the web app. For developers running locally, you'll need Ollama installed with the Mistral model."
      },
      {
        q: "Is my data secure?",
        a: "Yes! We don't store personal data. Analysis happens in real-time, and results are only shown to you. We use secure HTTPS connections for all data transfers."
      }
    ]
  },
  {
    category: "SDG & Impact",
    questions: [
      {
        q: "What are the UN SDGs?",
        a: "The United Nations Sustainable Development Goals (SDGs) are 17 global goals designed to achieve a better and more sustainable future. SkillTwin aligns with SDG 4 (Quality Education) and SDG 8 (Decent Work and Economic Growth)."
      },
      {
        q: "How does SkillTwin contribute to SDG 4?",
        a: "SkillTwin promotes quality education by identifying curriculum gaps, providing personalized learning paths, and connecting students with relevant resources to enhance their education."
      },
      {
        q: "How does SkillTwin contribute to SDG 8?",
        a: "SkillTwin promotes decent work by improving employability, providing real job market insights, and helping students develop skills that employers actually need."
      }
    ]
  }
]

function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [isOpen, setIsOpen] = useState(false)

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="border-b border-border/50 last:border-0"
    >
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full py-5 flex items-center justify-between text-left hover:text-primary transition-colors"
      >
        <span className="font-medium pr-8">{question}</span>
        <motion.div
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.2 }}
        >
          <ChevronDown className="h-5 w-5 text-muted-foreground flex-shrink-0" />
        </motion.div>
      </button>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="overflow-hidden"
          >
            <p className="pb-5 text-muted-foreground leading-relaxed">
              {answer}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  )
}

import { BackButton } from "@/components/ui/back-button"

export default function FAQPage() {
  return (
    <main className="min-h-screen bg-background">
      <Navbar />

      {/* Hero Section */}
      <section className="pt-32 pb-16">
        <div className="container px-4 mx-auto">
          <div className="max-w-3xl mx-auto mb-8">
            <BackButton />
          </div>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center max-w-3xl mx-auto"
          >
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary mb-6">
              <HelpCircle className="h-4 w-4" />
              <span className="text-sm font-medium">Help Center</span>
            </div>

            <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mb-6">
              Frequently Asked Questions
            </h1>

            <p className="text-lg text-muted-foreground">
              Find answers to common questions about SkillTwin,
              our AI-powered skill gap analyzer.
            </p>
          </motion.div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="pb-24">
        <div className="container px-4 mx-auto max-w-4xl">
          {faqs.map((category, categoryIndex) => (
            <motion.div
              key={category.category}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: categoryIndex * 0.1 }}
              className="mb-12"
            >
              {/* Category Header */}
              <h2 className="text-2xl font-bold mb-6 flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                  <Sparkles className="h-5 w-5 text-primary" />
                </div>
                {category.category}
              </h2>

              {/* Questions */}
              <div className="rounded-2xl border border-border/50 bg-card/50 backdrop-blur-sm overflow-hidden">
                {category.questions.map((faq, index) => (
                  <FAQItem key={index} question={faq.q} answer={faq.a} />
                ))}
              </div>
            </motion.div>
          ))}

          {/* Still Have Questions */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-16 p-8 rounded-2xl bg-primary/10 text-center"
          >
            <h3 className="text-xl font-semibold mb-3">Still have questions?</h3>
            <p className="text-muted-foreground mb-6">
              Can't find the answer you're looking for? Start your analysis and see SkillTwin in action!
            </p>
            <Button asChild size="lg">
              <Link href="/dashboard">
                Try SkillTwin Now
              </Link>
            </Button>
          </motion.div>
        </div>
      </section>

      <Footer />
    </main>
  )
}